/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Applicant;
import Model.Business;
import Model.Vaccine;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author forumkaria
 */
public
        class AddVaccineJPanel extends javax.swing.JPanel {
        Business business;
        DefaultTableModel petsTable;
        
    /**
     * Creates new form AddVaccineJPanel
     */
    public
            AddVaccineJPanel(Business b) {
        initComponents();
        
        this.petsTable = (DefaultTableModel) pets.getModel();
        this.business = b;
        displayPets();
        
    }

    public void displayPets(){
         ArrayList<Applicant> applicants = this.business.getApplicantsDirectory();

        if (applicants.size() > 0) {
            // display

            petsTable.setRowCount(0);
            
            for (Applicant a : applicants) {
              
                
                // number of columns in the table = 3 and row should be framed
                
                Object row[] = new Object[3];
                row[0] = a.getApplicantID();
                row[1] = a.getPet().getPetName();
                row[2] = a.getPet().getPetType();
                
                // add the row to the table
                petsTable.addRow(row);
            }
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VaccinationDetailsJLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        vaccineNameTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        courseCompletedCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        pets = new javax.swing.JTable();
        addVaccineBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        VaccinationDetailsJLabel.setText("ADD VACCINATION");

        jLabel11.setText("Vaccine Name:");

        jLabel13.setText("Course Completed: ");

        pets.setBackground(new java.awt.Color(102, 204, 255));
        pets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Applicant ID", "Pet Name", "Pet Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pets);

        addVaccineBtn.setBackground(new java.awt.Color(102, 153, 255));
        addVaccineBtn.setText("ADD");
        addVaccineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccineBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseCompletedCheckBox))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vaccineNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(VaccinationDetailsJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(addVaccineBtn)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(VaccinationDetailsJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(vaccineNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(courseCompletedCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addVaccineBtn)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addVaccineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccineBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = pets.getSelectedRow();
        
        Vaccine v = new Vaccine(vaccineNameTxt.getText(),courseCompletedCheckBox.isSelected(), (int) Math.random());
        
        Applicant a = this.business.findApplicantById(Integer.parseInt(String.valueOf(petsTable.getValueAt(selectedRow,0))));
        
        a.getPet().addToVaccinationHistory(v);
        
        JOptionPane.showMessageDialog(null, "Added to Pet's Vaccination History");
        
    }//GEN-LAST:event_addVaccineBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VaccinationDetailsJLabel;
    private javax.swing.JButton addVaccineBtn;
    private javax.swing.JCheckBox courseCompletedCheckBox;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pets;
    private javax.swing.JTextField vaccineNameTxt;
    // End of variables declaration//GEN-END:variables
}
