/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import AppSystem.AppSystem;
import Branch.Branch;
import Customer.Customer;
import Library.Library;
import Library.Material.Book;
import Library.Material.Magazine;
import Library.RentalRequest.RentalRequest;
import Useraccount.UserAccount;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author forumkaria
 */
public
        class BranchManagerJFrame extends javax.swing.JFrame {

    private AppSystem appSystem;
    private UserAccount userAccount;
    private DefaultTableModel materialTableModel;
    private DefaultTableModel requestTableModel;
    private Branch currentBranch;
    private Library currentLibrary;
    private Customer customer;
    /**
     * Creates new form BranchManagerJFrame
     */
    
    public BranchManagerJFrame() {
        initComponents();
    }
    
    public
            BranchManagerJFrame(AppSystem appSystem, Branch branch, UserAccount userAccount) {
                System.out.println("THISSS>>>>ISSSS");
        initComponents();
        this.setVisible(true);
        this.appSystem = appSystem;
        this.userAccount = userAccount;
        this.materialTableModel = (DefaultTableModel) materialTable.getModel();
        this.requestTableModel = (DefaultTableModel) reqTable.getModel();
        this.currentBranch = branch;
        this.currentLibrary = currentBranch.getLibrary();
        totalRev.setText(String.valueOf(currentLibrary.getRentalRequestDirectory().calculateTotalRevenue()));
        this.customer = this.appSystem.getCustomerDirectory().findById(userAccount.getAccountId());
        
        
        populateMaterial();
        populateRentalReq();
        
      
    }

    public void populateMaterial(){
        SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        materialTableModel.setRowCount(0);
        
            for (Book b : this.currentBranch.getLibrary().getBookDirectory().getBooks()) {
                Object[] row = new Object[14];
                
                row[0] = b.getMaterialId();
                row[1] = b.getMaterialType();
                row[2] = b.getName();
                row[3] = DateFormat.format(b.getDate());
                row[4] = b.getAuthor().getName();
                row[5] = b.getGenre().getGenre();
                row[6] = b.getPages();
                row[7] = b.getLanguage();
                row[8] = b.getBindingType();
                row[11] = b.getAvailability(b.getIsAvailable());
                row[12] = this.currentLibrary.getBuildingNo();
                row[13] = b.getPrice();

                materialTableModel.addRow(row);
            }
            for (Magazine m : this.currentBranch.getLibrary().getMagazineDirectory().getMagazines()) {
                Object[] row = new Object[14];
               
                row[0] = m.getMaterialId();
                row[1] = m.getMaterialType();
                row[2] = m.getName();
                row[3] = DateFormat.format(m.getDate());
                
                row[9] = m.getCompany();
                row[10] = m.getIssueType();
                row[11] = m.getAvailability(m.getIsAvailable());
                row[12] = this.currentLibrary.getBuildingNo();
                row[13] = m.getPrice();
                materialTableModel.addRow(row);
               }  
            }  
    
            public void populateRentalReq() {
        if (this.currentLibrary.getRentalRequestDirectory().getMasterRequestList().size() > 0) {
            requestTableModel.setRowCount(0);
            for (RentalRequest rr : this.currentLibrary.getRentalRequestDirectory().getMasterRequestList()) {

                Object[] row = new Object[8];

                row[0] = rr;
                row[1] = rr.getCustomer().getId();
                row[2] = (rr.getBook() == null) ? "-" : rr.getBook().getName();
                row[3] = (rr.getMagazine() == null) ? "-" : rr.getMagazine().getName();
                row[4] = rr.getDuration();
                row[5] = rr.getPrice();
                row[6] = rr.getStatus();
                row[7] = rr.getBranchName();

                requestTableModel.addRow(row);
            }
        }
        
        
    }
        public int calBranchRevenue(){
        int rev = this.currentLibrary.getRentalRequestDirectory().calculateTotalRevenue();
        
        return rev;
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        materialTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reqTable = new javax.swing.JTable();
        RentReqRec = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        totalRev = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        materialTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Name", "Date", "Author", "Genre", "No of Pages", "Language", "Binding type", "Company Name", "Issue Type", "Availability", "Library", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        materialTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(materialTable);
        if (materialTable.getColumnModel().getColumnCount() > 0) {
            materialTable.getColumnModel().getColumn(11).setResizable(false);
            materialTable.getColumnModel().getColumn(13).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        jLabel1.setText("MATERIAL COLLECTION");

        reqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Id", "Customer Id", "Book", "Magazine", "Duration", "Price", "Status", "Library"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reqTable);

        RentReqRec.setFont(new java.awt.Font("Big Caslon", 1, 14)); // NOI18N
        RentReqRec.setText("RENTAL REQUESTS RECEIVED");

        jLabel2.setText("TOTAL REVENUE");

        logoutBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        totalRev.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(RentReqRec))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel2)
                        .addGap(81, 81, 81)
                        .addComponent(totalRev, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(logoutBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(RentReqRec)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(logoutBtn)
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materialTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialTableMouseClicked

    }//GEN-LAST:event_materialTableMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainJFrame mj = new MainJFrame(this.appSystem);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public
                    void run() {
                new BranchManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RentReqRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable materialTable;
    private javax.swing.JTable reqTable;
    private javax.swing.JTextField totalRev;
    // End of variables declaration//GEN-END:variables
}
