/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Contact;
import Model.Recipe;
import Model.Person;
import java.awt.event.KeyEvent;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author forumkaria
 */
public
        class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Person person;
    public
            CreateJPanel(Person person) {
        initComponents();
        
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ChefsDetails = new javax.swing.JLabel();
        ChefFirstName = new javax.swing.JLabel();
        ChefLastName = new javax.swing.JLabel();
        ChefUserName = new javax.swing.JLabel();
        RecipeTitle = new javax.swing.JLabel();
        NoOfServings = new javax.swing.JLabel();
        IsGlutenFree = new javax.swing.JLabel();
        DifficultyLevel = new javax.swing.JLabel();
        NoOfIngredients = new javax.swing.JLabel();
        CategoryOfFood = new javax.swing.JLabel();
        RecipeDescription = new javax.swing.JLabel();
        ChefPhoneNumber = new javax.swing.JLabel();
        ChefEmailID = new javax.swing.JLabel();
        fieldLastname = new javax.swing.JTextField();
        fieldUsername = new javax.swing.JTextField();
        fieldPhNo = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        fieldFirstname = new javax.swing.JTextField();
        fieldRecipeTitle = new javax.swing.JTextField();
        fieldServings = new javax.swing.JTextField();
        fieldIngredients = new javax.swing.JTextField();
        fieldCategory = new javax.swing.JTextField();
        fieldDescription = new javax.swing.JTextField();
        fieldDifficulty = new javax.swing.JTextField();
        CreateRecipeButton = new javax.swing.JButton();
        ChefsRecipeDetails = new javax.swing.JLabel();
        setImageBrowseButton = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        checkboxGlutenFree = new javax.swing.JCheckBox();

        ChefsDetails.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        ChefsDetails.setText("CHEF's DETAILS");

        ChefFirstName.setText("First Name");

        ChefLastName.setText("Last Name");

        ChefUserName.setText("Username");

        RecipeTitle.setText("Recipe Title");

        NoOfServings.setText("Number of Servings ");

        IsGlutenFree.setText("Is this recipe gluten free?");

        DifficultyLevel.setText("Difficulty Level");

        NoOfIngredients.setText("Number of Ingredients");

        CategoryOfFood.setText("Category of Food");

        RecipeDescription.setText("Recipe Description");

        ChefPhoneNumber.setText("Phone Number ");

        ChefEmailID.setText("Email ID");

        fieldLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastnameActionPerformed(evt);
            }
        });
        fieldLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldLastnameKeyTyped(evt);
            }
        });

        fieldPhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPhNoActionPerformed(evt);
            }
        });
        fieldPhNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldPhNoKeyTyped(evt);
            }
        });

        fieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldEmailKeyTyped(evt);
            }
        });

        fieldFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstnameActionPerformed(evt);
            }
        });
        fieldFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldFirstnameKeyTyped(evt);
            }
        });

        fieldServings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldServingsKeyTyped(evt);
            }
        });

        fieldIngredients.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldIngredientsKeyTyped(evt);
            }
        });

        fieldDifficulty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldDifficultyKeyTyped(evt);
            }
        });

        CreateRecipeButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        CreateRecipeButton.setText("Create");
        CreateRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRecipeButtonActionPerformed(evt);
            }
        });

        ChefsRecipeDetails.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        ChefsRecipeDetails.setText("CHEF's RECIPE DETAILS");

        setImageBrowseButton.setText("Set Image");
        setImageBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setImageBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChefPhoneNumber)
                    .addComponent(ChefEmailID)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ChefsDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(ChefsRecipeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChefLastName)
                            .addComponent(ChefUserName)
                            .addComponent(ChefFirstName))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldPhNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fieldServings, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RecipeTitle)
                            .addComponent(IsGlutenFree)
                            .addComponent(DifficultyLevel)
                            .addComponent(NoOfIngredients)
                            .addComponent(CategoryOfFood)
                            .addComponent(RecipeDescription)
                            .addComponent(NoOfServings)
                            .addComponent(setImageBrowseButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CreateRecipeButton)
                        .addGap(98, 98, 98)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldRecipeTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(checkboxGlutenFree)
                                .addGap(123, 123, 123)))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChefsDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChefsRecipeDetails))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChefFirstName)
                    .addComponent(fieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecipeTitle)
                    .addComponent(fieldRecipeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChefLastName)
                    .addComponent(fieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoOfServings)
                    .addComponent(fieldServings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChefUserName)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IsGlutenFree)
                    .addComponent(checkboxGlutenFree, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChefPhoneNumber)
                    .addComponent(fieldPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DifficultyLevel)
                    .addComponent(fieldDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChefEmailID)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoOfIngredients)
                    .addComponent(fieldIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CategoryOfFood)
                        .addGap(27, 27, 27)
                        .addComponent(RecipeDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setImageBrowseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(CreateRecipeButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastnameActionPerformed

    private void fieldLastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldLastnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastnameKeyTyped

    private void fieldPhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPhNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPhNoActionPerformed

    private void fieldPhNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPhNoKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldPhNoKeyTyped

    private void fieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailKeyTyped

    private void fieldFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstnameActionPerformed

    private void fieldFirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldFirstnameKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fieldFirstnameKeyTyped

    private void fieldServingsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldServingsKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldServingsKeyTyped

    private void fieldIngredientsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIngredientsKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldIngredientsKeyTyped

    private void fieldDifficultyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDifficultyKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fieldDifficultyKeyTyped

    private void CreateRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRecipeButtonActionPerformed
        // TODO add your handling code here:
        
        if (fieldFirstname.getText().isEmpty() || fieldLastname.getText().isEmpty() || fieldUsername.getText().isEmpty() || fieldPhNo.getText().isEmpty() || fieldEmail.getText().isEmpty() || fieldRecipeTitle.getText().isEmpty() || fieldCategory.getText().isEmpty() || fieldDescription.getText().isEmpty() || fieldDifficulty.getText().isEmpty() 
                || fieldServings.getText().isEmpty() || fieldIngredients.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Some fields are blank. You must fill them before saving!");
        } 
        
        //Binding User input to the person object
        person.setFirstname(fieldFirstname.getText());
        person.setLastname(fieldLastname.getText());
        person.setUsername(fieldUsername.getText());
        
        Contact contact = this.person.getContact(); 
        contact.setPhoneNumber(Long.valueOf(fieldPhNo.getText()));
        
        Recipe recipe = this.person.getRecipe();
        recipe.setRecipeTitle(fieldRecipeTitle.getText());
        recipe.setNoOfServings(Integer.valueOf(fieldServings.getText()));
        recipe.setIsGlutenFree(Boolean.valueOf(checkboxGlutenFree.isSelected()));
        recipe.setDiffLevel(Float.valueOf(fieldDifficulty.getText()));
        recipe.setNoOfIngredients(Integer.valueOf(fieldIngredients.getText()));
        recipe.setCategory(fieldCategory.getText());
        recipe.setDescription(fieldDescription.getText());
        
        
        JOptionPane.showMessageDialog(null, "Successfully Created Chef and Recipe Information!");

    }//GEN-LAST:event_CreateRecipeButtonActionPerformed

    private void setImageBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setImageBrowseButtonActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_setImageBrowseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryOfFood;
    private javax.swing.JLabel ChefEmailID;
    private javax.swing.JLabel ChefFirstName;
    private javax.swing.JLabel ChefLastName;
    private javax.swing.JLabel ChefPhoneNumber;
    private javax.swing.JLabel ChefUserName;
    private javax.swing.JLabel ChefsDetails;
    private javax.swing.JLabel ChefsRecipeDetails;
    private javax.swing.JButton CreateRecipeButton;
    private javax.swing.JLabel DifficultyLevel;
    private javax.swing.JLabel IsGlutenFree;
    private javax.swing.JLabel NoOfIngredients;
    private javax.swing.JLabel NoOfServings;
    private javax.swing.JLabel RecipeDescription;
    private javax.swing.JLabel RecipeTitle;
    private javax.swing.JCheckBox checkboxGlutenFree;
    private javax.swing.JTextField fieldCategory;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JTextField fieldDifficulty;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldFirstname;
    private javax.swing.JTextField fieldIngredients;
    private javax.swing.JTextField fieldLastname;
    private javax.swing.JTextField fieldPhNo;
    private javax.swing.JTextField fieldRecipeTitle;
    private javax.swing.JTextField fieldServings;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton setImageBrowseButton;
    // End of variables declaration//GEN-END:variables
}
