/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Contact;
import Model.Recipe;
import Model.Person;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author forumkaria
 */
public
        class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Person person;
    public
            CreateJPanel(Person person) {
        initComponents();
        
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmakhni = new javax.swing.JPanel();
        ChefsDetails = new javax.swing.JLabel();
        ChefFirstName = new javax.swing.JLabel();
        ChefLastName = new javax.swing.JLabel();
        ChefUserName = new javax.swing.JLabel();
        RecipeTitle = new javax.swing.JLabel();
        NoOfServings = new javax.swing.JLabel();
        IsGlutenFree = new javax.swing.JLabel();
        DifficultyLevel = new javax.swing.JLabel();
        NoOfIngredients = new javax.swing.JLabel();
        CategoryOfFood = new javax.swing.JLabel();
        RecipeDescription = new javax.swing.JLabel();
        ChefPhoneNumber = new javax.swing.JLabel();
        ChefEmailID = new javax.swing.JLabel();
        fieldLastname = new javax.swing.JTextField();
        fieldUsername = new javax.swing.JTextField();
        fieldPhNo = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        fieldFirstname = new javax.swing.JTextField();
        fieldRecipeTitle = new javax.swing.JTextField();
        fieldServings = new javax.swing.JTextField();
        fieldIngredients = new javax.swing.JTextField();
        fieldCategory = new javax.swing.JTextField();
        fieldDescription = new javax.swing.JTextField();
        CreateRecipeButton = new javax.swing.JButton();
        ChefsRecipeDetails = new javax.swing.JLabel();
        setImageBrowseButton = new javax.swing.JButton();
        makhniImage = new javax.swing.JLabel();
        checkboxGlutenFree = new javax.swing.JCheckBox();
        difficultyLevel = new javax.swing.JSlider();

        pmakhni.setBackground(new java.awt.Color(153, 153, 255));
        pmakhni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChefsDetails.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        ChefsDetails.setText("CHEF's DETAILS");
        pmakhni.add(ChefsDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 24, 260, 42));

        ChefFirstName.setText("First Name");
        pmakhni.add(ChefFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 107, -1, -1));

        ChefLastName.setText("Last Name");
        pmakhni.add(ChefLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 151, -1, -1));

        ChefUserName.setText("Username");
        pmakhni.add(ChefUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 195, -1, -1));

        RecipeTitle.setText("Recipe Title");
        pmakhni.add(RecipeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 107, -1, -1));

        NoOfServings.setText("Number of Servings ");
        pmakhni.add(NoOfServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 151, -1, -1));

        IsGlutenFree.setText("Is this recipe gluten free?");
        pmakhni.add(IsGlutenFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 195, -1, -1));

        DifficultyLevel.setText("Difficulty Level");
        pmakhni.add(DifficultyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 243, -1, -1));

        NoOfIngredients.setText("Number of Ingredients");
        pmakhni.add(NoOfIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 287, -1, -1));

        CategoryOfFood.setText("Category of Food");
        pmakhni.add(CategoryOfFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 326, -1, -1));

        RecipeDescription.setText("Recipe Description");
        pmakhni.add(RecipeDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 369, -1, -1));

        ChefPhoneNumber.setText("Phone Number ");
        pmakhni.add(ChefPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 243, -1, -1));

        ChefEmailID.setText("Email ID");
        pmakhni.add(ChefEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 287, -1, -1));

        fieldLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastnameActionPerformed(evt);
            }
        });
        fieldLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldLastnameKeyTyped(evt);
            }
        });
        pmakhni.add(fieldLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 146, 100, -1));
        pmakhni.add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 190, 100, -1));

        fieldPhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPhNoActionPerformed(evt);
            }
        });
        fieldPhNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldPhNoKeyTyped(evt);
            }
        });
        pmakhni.add(fieldPhNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 238, 100, -1));

        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });
        fieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldEmailKeyTyped(evt);
            }
        });
        pmakhni.add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 282, 101, -1));

        fieldFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstnameActionPerformed(evt);
            }
        });
        fieldFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldFirstnameKeyTyped(evt);
            }
        });
        pmakhni.add(fieldFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 102, 100, -1));
        pmakhni.add(fieldRecipeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 102, 117, -1));

        fieldServings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldServingsKeyTyped(evt);
            }
        });
        pmakhni.add(fieldServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 146, 117, -1));

        fieldIngredients.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldIngredientsKeyTyped(evt);
            }
        });
        pmakhni.add(fieldIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 282, 117, -1));
        pmakhni.add(fieldCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 326, 117, -1));
        pmakhni.add(fieldDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 364, 117, -1));

        CreateRecipeButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        CreateRecipeButton.setText("Create");
        CreateRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRecipeButtonActionPerformed(evt);
            }
        });
        pmakhni.add(CreateRecipeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 587, -1, -1));

        ChefsRecipeDetails.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        ChefsRecipeDetails.setText("CHEF's RECIPE DETAILS");
        pmakhni.add(ChefsRecipeDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 15, 452, -1));

        setImageBrowseButton.setText("Set Image");
        setImageBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setImageBrowseButtonActionPerformed(evt);
            }
        });
        pmakhni.add(setImageBrowseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 441, -1, 41));

        makhniImage.setBackground(new java.awt.Color(153, 204, 255));
        pmakhni.add(makhniImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 427, 229, 253));
        pmakhni.add(checkboxGlutenFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, -1, 26));
        pmakhni.add(difficultyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 222, 142, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pmakhni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pmakhni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastnameActionPerformed

    private void fieldLastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldLastnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastnameKeyTyped

    private void fieldPhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPhNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPhNoActionPerformed

    private void fieldPhNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldPhNoKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldPhNoKeyTyped

    private void fieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailKeyTyped

    private void fieldFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstnameActionPerformed

    private void fieldFirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldFirstnameKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fieldFirstnameKeyTyped

    private void fieldServingsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldServingsKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldServingsKeyTyped

    private void fieldIngredientsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIngredientsKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_fieldIngredientsKeyTyped

    private void CreateRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRecipeButtonActionPerformed
        // TODO add your handling code here:
        
        if (fieldFirstname.getText().isEmpty() || fieldLastname.getText().isEmpty() || fieldUsername.getText().isEmpty() || 
            (fieldPhNo.getText().isEmpty() || fieldPhNo.getText().length()<9)
                || fieldEmail.getText().isEmpty() || fieldRecipeTitle.getText().isEmpty() || 
                fieldCategory.getText().isEmpty() 
                || fieldDescription.getText().isEmpty()
                || (fieldServings.getText().isEmpty() || Integer.parseInt(fieldServings.getText()) <=0)
                || fieldIngredients.getText().isEmpty() || Integer.parseInt(fieldIngredients.getText()) <=0 ) {
            JOptionPane.showMessageDialog(null, "Some fields are blank or incomplete. You must fill them before saving!");
        } else {
            if(!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", fieldEmail.getText()))){
            JOptionPane.showMessageDialog(null, "Invalid Email format");
        } 
            
            else{
            
        
        //Binding User input to the person object
        person.setFirstname(fieldFirstname.getText());
        person.setLastname(fieldLastname.getText());
        person.setUsername(fieldUsername.getText());
        
        Contact contact = this.person.getContact(); 
        contact.setPhoneNumber(Long.valueOf(fieldPhNo.getText()));
        contact.setEmailID(fieldEmail.getText());
        
        Recipe recipe = this.person.getRecipe();
        recipe.setRecipeTitle(fieldRecipeTitle.getText());
        recipe.setNoOfServings(Integer.valueOf(fieldServings.getText()));
        recipe.setIsGlutenFree(Boolean.valueOf(checkboxGlutenFree.isSelected()));
        recipe.setDiffLevel(Float.valueOf(difficultyLevel.getValue()));
        recipe.setNoOfIngredients(Integer.valueOf(fieldIngredients.getText()));
        recipe.setCategory(fieldCategory.getText());
        recipe.setDescription(fieldDescription.getText());
        
        
        JOptionPane.showMessageDialog(null, "Successfully Created Chef and Recipe Information!");
        }}
    }//GEN-LAST:event_CreateRecipeButtonActionPerformed

    private void setImageBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setImageBrowseButtonActionPerformed
        // TODO add your handling code here:

        JFileChooser browseImageFile = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
         
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            ImageIcon ii = new ImageIcon(selectedImagePath);
            this.person.getRecipe().setImagePath(selectedImagePath);
            //Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(makhniImage.getWidth(), makhniImage.getHeight(), Image.SCALE_SMOOTH);
             
            makhniImage.setIcon(new ImageIcon(image));
        }       
    }//GEN-LAST:event_setImageBrowseButtonActionPerformed

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryOfFood;
    private javax.swing.JLabel ChefEmailID;
    private javax.swing.JLabel ChefFirstName;
    private javax.swing.JLabel ChefLastName;
    private javax.swing.JLabel ChefPhoneNumber;
    private javax.swing.JLabel ChefUserName;
    private javax.swing.JLabel ChefsDetails;
    private javax.swing.JLabel ChefsRecipeDetails;
    private javax.swing.JButton CreateRecipeButton;
    private javax.swing.JLabel DifficultyLevel;
    private javax.swing.JLabel IsGlutenFree;
    private javax.swing.JLabel NoOfIngredients;
    private javax.swing.JLabel NoOfServings;
    private javax.swing.JLabel RecipeDescription;
    private javax.swing.JLabel RecipeTitle;
    private javax.swing.JCheckBox checkboxGlutenFree;
    private javax.swing.JSlider difficultyLevel;
    private javax.swing.JTextField fieldCategory;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldFirstname;
    private javax.swing.JTextField fieldIngredients;
    private javax.swing.JTextField fieldLastname;
    private javax.swing.JTextField fieldPhNo;
    private javax.swing.JTextField fieldRecipeTitle;
    private javax.swing.JTextField fieldServings;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel makhniImage;
    private javax.swing.JPanel pmakhni;
    private javax.swing.JButton setImageBrowseButton;
    // End of variables declaration//GEN-END:variables
}
